on:
  push:
    branches: [main]
  pull_request:
name: Flatpak Builder
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Flatpak Builder
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: io.github.heliguy4599.FlattoolGUI.flatpak
        manifest-path: io.github.heliguy4599.FlattoolGUI.json
        repository-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo